---
repos:
  - repo: "https://github.com/psf/black"
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=79]
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-xml
      - id: check-json
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: "https://github.com/asottile/blacken-docs"
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==19.3b0
  - repo: "https://github.com/asottile/setup-cfg-fmt"
    rev: v1.15.0
    hooks:
      - id: setup-cfg-fmt
  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: v1.6.0
    hooks:
      - id: rst-backticks
  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: v1.25.0
    hooks:
      - id: yamllint
        args:
          - "--format"
          - parsable
          - "--strict"
  - repo: "https://github.com/Lucas-C/pre-commit-hooks-lxml"
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
  - repo: "https://github.com/Lucas-C/pre-commit-hooks-markup"
    rev: v1.0.0
    hooks:
      - id: rst-linter
  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
