---

dist: xenial
language: python
python: 3.8.3
install:
  - pip install -r requirements_dev.txt
  - pip install tox-travis
script:
  - black --line-length=79 --check .
  - tox
env:
  - PYTHONBREAKPOINT=0 DJANGO_ENVIRONMENT=DEVELOPMENT DJANGO_HOST_NAME=localhost
